\documentclass[ english, a4paper, DIV=calc, BCOR=0mm, fontsize=10pt, pagesize, fleqn ]{scrbook}

\usepackage{wisperFontSetupTexGyreAndFira}
\usepackage{wisperKOMAMisc}
\KOMAoptions{DIV=last}
\usepackage{wisperFootnotecite}
\usepackage{wisperNumericSupercite}
\usepackage{wisperIfTwoside}
\usepackage{wisperTwosideFloats}
\usepackage{sidenotes}
\usepackage{wisperBoxes}
\usepackage{paul-tol-colors}
\PassOptionsToPackage {main=english} {babel} 


% vim: ft=tex ts=2 sw=2 et fdm=marker fmr=[[[,]]]:
