\documentclass[ twocolumn, english, DIV=14, fontsize=10pt ]{scrartcl}

\usepackage{wisperFontsTexGyre}
%\usepackage{wisperNumericSupercite}
\usepackage[maxcitenames=1]{biblatex}
\usepackage{wisperBiblatexAlphabetic}
\usepackage{caption}

\captionsetup{
	format=plain,
	%font=small,
	font={sf,footnotesize},
	labelfont=sc,
	margin=0.1\linewidth,
	justification=RaggedRight
% \numberwithin{equation}{section}
\PassOptionsToPackage {main=english} {babel} 


% vim: ft=tex ts=2 sw=2 et fdm=marker fmr=[[[,]]]:
