\documentclass[ a4paper, english, BCOR=0mm, DIV=10, fontsize=10pt, pagesize ]{scrartcl}

\usepackage{wisperFontsTexGyre}
%\usepackage{wisperNumericSupercite}
\usepackage{caption}

\captionsetup{
	format=plain,
	%font=small,
	font={sf,footnotesize},
	labelfont=sc,
	calcwidth=0.9\linewidth,
	justification=RaggedRight
\numberwithin{equation}{section}
\PassOptionsToPackage {main=english} {babel} 


% vim: ft=tex ts=2 sw=2 et fdm=marker fmr=[[[,]]]:
